# THIS IS THE EXACT FORMAT VERL EXPECTS - DO NOT DEVIATE
tools:
  - class_name: "memupdate.tools.manage_memory.ManageMemoryTool"
    config:
      type: "native"
      max_content_length: 1000
      auto_type_detection: true
      enable_metadata: true

  - class_name: "memupdate.tools.search_memory.SearchMemoryTool"
    config:
      type: "native"  # REQUIRED: Must be "native" for custom tools
      max_results: 10
      default_top_k: 5
      similarity_threshold: 0.3
        
      
  - class_name: "memupdate.tools.sample_memory.SampleMemoryTool"
    config:
      type: "native"
      max_sample_size: 10
      default_strategy: "random"
      